

services:
  backend:
    build:
      context: ./backend
    container_name: express_backend
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234567890
      - DB_NAME=Express_user
      - DB_PORT=5432
      - JWT_SECRET= BsOvxnHmafCbKAxiyjzK+4pcbqiulUmeXnzkVN7ND5A=
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: Express_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
